### ISSUE TITLE
Proxies seem to get banned fast

### ISSUE THREAD

**Issue by MilanHarrisDev** [OGSegu/Twitch-View-Bot#3]
Hi. I am testing out your software, and it works at first, but then after a little while the viewercount goes back down. When I get a new set of proxies, it works again. Do you know what might cause this? or how to fix?

**Comment by MilanHarrisDev** [comment]
Also, do you have any recommendations on where to get good proxies? I've been trying webshare.

**Comment by OGSegu** [comment]
Looks like your proxies are not good at all. 
You need to use only HTTPS type and it needs to be really high quality. I can't recommend a proxy service, but any top ones will give you the result which you want.

**Comment by MilanHarrisDev** [comment]
Alright. thank you for the advice. will try others soon

**Comment by nick0zer** [comment]
Don't get fooled, the problem is not on the proxies. With a good viewbot you can get even with public proxies up to 100-250 viewers. It's usually the method viewbots sending the views gets flagged by twitch and removes the view after a certain amount of time, for example, viewers that got the video sound turned off won't count as a viewer after a certain amount of time.

**Comment by OGSegu** [comment]
> 
> 
> Don't get fooled, the problem is not on the proxies. With a good viewbot you can get even with public proxies up to 100-250 viewers. It's usually the method viewbots sending the views gets flagged by twitch and removes the view after a certain amount of time, for example, viewers that got the video sound turned off won't count as a viewer after a certain amount of time.

Every your word is incorrect. Firstly, you can't get 100-250 viewers with public proxies, because they are already blocked by Twitch or will be blocked in 5 mins. Secondly, this method used by most paid view bots, including RuBot and there's no other way to send a view by request except slow Selenium which is awful. The only thing that can improve the work of my viewbot is to add a bunch of client ids, so you can't get limited by Twitch API. I heard this theory about video sound, but this is nonsense because you don't send any requests when you turn off sound. If you have any arguments with proves, I will be glad to have a discussion
